name: release-build

on:
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'zulu'
          cache: gradle
      - name: Build and Zip extension
        uses: gradle/gradle-build-action@v2
        with:
          arguments: buildAndZip
      - uses: actions/upload-artifact@v3
        name: Upload Zip to Github Packages
        with:
          name: 'packed-extension'
          path: './build/twitch-kino-*.zip'
      - id: 'previous-tag'
        name: Get Previous tag
        if: ${{ github.ref_name == 'master' }}
        uses: WyriHaximus/github-action-get-previous-tag@v1
      - id: 'create-release'
        name: Create Github release
        if: ${{ github.ref_name == 'master' }}
        uses: softprops/action-gh-release@v1
        with:
          files: './build/twitch-kino-*.zip'
          draft: true
          tag_name: ${{ steps.previous-tag.outputs.tag }}
          name: v${{ steps.previous-tag.outputs.tag }}
